// types/llm-judge.ts

import { LanguageSpecificRubricScores, HarmDisparityMetrics } from './';

/**
 * A version of the rubric scores that an LLM can realistically produce.
 * It excludes the `entities` field which requires external verification and is instead handled by human evaluators.
 */
export type LlmRubricScores = Omit<LanguageSpecificRubricScores, 'entities'>;

/**
 * Represents the evaluation scores and notes as generated by an LLM judge.
 */
export interface LlmEvaluation {
  english: LlmRubricScores;
  native: LlmRubricScores;
  disparity: HarmDisparityMetrics;
  notes: string;
}
